#!/usr/bin/env python3
try:
    print("enter your player's health")
    H = int(input("-->"))
    print("enter the Attack Type")
    AT= str(input("-->"))

    if AT == "punch":
        Final = H - 10
        N = True

    elif AT == "kick":
        Final = H - 20
        N = True

    elif AT == "magic":
        Final = H - 30
        N = True

    else:
        print("Enter a supported input!!")

    if N == True and Final >= 0:
        print(f"Here's your player's health {Final}")
    elif N == True and Final < 0:
        print("Game Over!")
except ValueError:
    print("Input Error; fill the first input with a number and the second with an attack type 'punch, kick or magic' Warning: 'Case Sensitive!!'")
