#!/usr/bin/env python
# coding: utf-8
import tkinter as tk
from tkinter import messagebox, ttk
root = tk.Tk()
root.title("Username Length Check")
L = ttk.Label(root, text = "Enter Your Username!")
L.pack()

E = ttk.Entry(root)
E.pack()

def submit():
    UN = str(E.get())

    if len(UN) > 5:
        Var = "Username Accepted"
    else:
        Var = "Username Denied 'too short'"

    messagebox.showinfo(
        "User Name Status",
        Var
        )

B = tk.Button(root, text = "Click To Submit!", fg = "blue", bg = "grey", command = submit)
B.pack()


root.mainloop()


Page = tk.Tk()
Page.title("Saad's Calculator")
